apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auto-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50



